DROP TABLE IF EXISTS TBL_BOOKS;
  
CREATE TABLE TBL_BOOKS (
  BOOK_ID IDENTITY PRIMARY KEY,
  BOOK_NAME VARCHAR(250) NOT NULL,
  BOOK_TAGS VARCHAR(250),
  BOOK_RELEASE_DATE VARCHAR(250) NOT NULL,
  BOOK_IMAGE VARCHAR(250),
  BOOK_PRICE NUMBER(10, 2),
  BOOK_RATING NUMBER,
  BOOK_DESCRIPTION VARCHAR(250) NOT NULL
);
